//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControlCMMI.ControWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioSVN", Namespace="http://schemas.datacontract.org/2004/07/ServicioKSDP")]
    [System.SerializableAttribute()]
    public partial class UsuarioSVN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ServicioKSDP")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioFirmado", Namespace="http://schemas.datacontract.org/2004/07/ServicioKSDP")]
    [System.SerializableAttribute()]
    public partial class UsuarioFirmado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InicialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((this.IdEmpleadoField.Equals(value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpresa {
            get {
                return this.IdEmpresaField;
            }
            set {
                if ((this.IdEmpresaField.Equals(value) != true)) {
                    this.IdEmpresaField = value;
                    this.RaisePropertyChanged("IdEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPuesto {
            get {
                return this.IdPuestoField;
            }
            set {
                if ((this.IdPuestoField.Equals(value) != true)) {
                    this.IdPuestoField = value;
                    this.RaisePropertyChanged("IdPuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iniciales {
            get {
                return this.InicialesField;
            }
            set {
                if ((object.ReferenceEquals(this.InicialesField, value) != true)) {
                    this.InicialesField = value;
                    this.RaisePropertyChanged("Iniciales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://schemas.datacontract.org/2004/07/ServicioKSDP")]
    [System.SerializableAttribute()]
    public partial class Menu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdernarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMenuPadreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordernar {
            get {
                return this.OrdernarField;
            }
            set {
                if ((this.OrdernarField.Equals(value) != true)) {
                    this.OrdernarField = value;
                    this.RaisePropertyChanged("Ordernar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMenu {
            get {
                return this.idMenuField;
            }
            set {
                if ((this.idMenuField.Equals(value) != true)) {
                    this.idMenuField = value;
                    this.RaisePropertyChanged("idMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMenuPadre {
            get {
                return this.idMenuPadreField;
            }
            set {
                if ((this.idMenuPadreField.Equals(value) != true)) {
                    this.idMenuPadreField = value;
                    this.RaisePropertyChanged("idMenuPadre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ticket", Namespace="http://schemas.datacontract.org/2004/07/ServicioKSDP")]
    [System.SerializableAttribute()]
    public partial class Ticket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketKSDPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEnlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEtapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLiderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSubEtapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketKSDP {
            get {
                return this.TicketKSDPField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketKSDPField, value) != true)) {
                    this.TicketKSDPField = value;
                    this.RaisePropertyChanged("TicketKSDP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEnlace {
            get {
                return this.idEnlaceField;
            }
            set {
                if ((this.idEnlaceField.Equals(value) != true)) {
                    this.idEnlaceField = value;
                    this.RaisePropertyChanged("idEnlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEtapa {
            get {
                return this.idEtapaField;
            }
            set {
                if ((this.idEtapaField.Equals(value) != true)) {
                    this.idEtapaField = value;
                    this.RaisePropertyChanged("idEtapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLider {
            get {
                return this.idLiderField;
            }
            set {
                if ((this.idLiderField.Equals(value) != true)) {
                    this.idLiderField = value;
                    this.RaisePropertyChanged("idLider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPMO {
            get {
                return this.idPMOField;
            }
            set {
                if ((this.idPMOField.Equals(value) != true)) {
                    this.idPMOField = value;
                    this.RaisePropertyChanged("idPMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSistema {
            get {
                return this.idSistemaField;
            }
            set {
                if ((this.idSistemaField.Equals(value) != true)) {
                    this.idSistemaField = value;
                    this.RaisePropertyChanged("idSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSubEtapa {
            get {
                return this.idSubEtapaField;
            }
            set {
                if ((this.idSubEtapaField.Equals(value) != true)) {
                    this.idSubEtapaField = value;
                    this.RaisePropertyChanged("idSubEtapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTicket {
            get {
                return this.idTicketField;
            }
            set {
                if ((this.idTicketField.Equals(value) != true)) {
                    this.idTicketField = value;
                    this.RaisePropertyChanged("idTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipo {
            get {
                return this.idTipoField;
            }
            set {
                if ((this.idTipoField.Equals(value) != true)) {
                    this.idTipoField = value;
                    this.RaisePropertyChanged("idTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListItem", Namespace="http://schemas.datacontract.org/2004/07/ServicioKSDP")]
    [System.SerializableAttribute()]
    public partial class ListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item {
            get {
                return this.itemField;
            }
            set {
                if ((object.ReferenceEquals(this.itemField, value) != true)) {
                    this.itemField = value;
                    this.RaisePropertyChanged("item");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataRepTicket", Namespace="http://schemas.datacontract.org/2004/07/ServicioKSDP")]
    [System.SerializableAttribute()]
    public partial class DataRepTicket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTicketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sistema {
            get {
                return this.SistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaField, value) != true)) {
                    this.SistemaField = value;
                    this.RaisePropertyChanged("Sistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTicket {
            get {
                return this.idTicketField;
            }
            set {
                if ((this.idTicketField.Equals(value) != true)) {
                    this.idTicketField = value;
                    this.RaisePropertyChanged("idTicket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControWS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerUsuarioSVN", ReplyAction="http://tempuri.org/IService1/ObtenerUsuarioSVNResponse")]
        AppControlCMMI.ControWS.UsuarioSVN ObtenerUsuarioSVN(int idUsuario, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerUsuarioSVN", ReplyAction="http://tempuri.org/IService1/ObtenerUsuarioSVNResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.UsuarioSVN> ObtenerUsuarioSVNAsync(int idUsuario, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarUsuarioSVN", ReplyAction="http://tempuri.org/IService1/AgregarUsuarioSVNResponse")]
        bool AgregarUsuarioSVN(AppControlCMMI.ControWS.UsuarioSVN uSVN, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarUsuarioSVN", ReplyAction="http://tempuri.org/IService1/AgregarUsuarioSVNResponse")]
        System.Threading.Tasks.Task<bool> AgregarUsuarioSVNAsync(AppControlCMMI.ControWS.UsuarioSVN uSVN, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Acceso", ReplyAction="http://tempuri.org/IService1/AccesoResponse")]
        AppControlCMMI.ControWS.UsuarioFirmado Acceso(AppControlCMMI.ControWS.Usuario user, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Acceso", ReplyAction="http://tempuri.org/IService1/AccesoResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.UsuarioFirmado> AccesoAsync(AppControlCMMI.ControWS.Usuario user, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Menu", ReplyAction="http://tempuri.org/IService1/MenuResponse")]
        AppControlCMMI.ControWS.Menu[] Menu(int idPerfil, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Menu", ReplyAction="http://tempuri.org/IService1/MenuResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.Menu[]> MenuAsync(int idPerfil, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregaTicket", ReplyAction="http://tempuri.org/IService1/AgregaTicketResponse")]
        AppControlCMMI.ControWS.AgregaTicketResponse AgregaTicket(AppControlCMMI.ControWS.AgregaTicketRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregaTicket", ReplyAction="http://tempuri.org/IService1/AgregaTicketResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.AgregaTicketResponse> AgregaTicketAsync(AppControlCMMI.ControWS.AgregaTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmpresa", ReplyAction="http://tempuri.org/IService1/GetEmpresaResponse")]
        AppControlCMMI.ControWS.ListItem[] GetEmpresa(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmpresa", ReplyAction="http://tempuri.org/IService1/GetEmpresaResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetEmpresaAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTipo", ReplyAction="http://tempuri.org/IService1/GetTipoResponse")]
        AppControlCMMI.ControWS.ListItem[] GetTipo(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTipo", ReplyAction="http://tempuri.org/IService1/GetTipoResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetTipoAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSistema", ReplyAction="http://tempuri.org/IService1/GetSistemaResponse")]
        AppControlCMMI.ControWS.ListItem[] GetSistema(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSistema", ReplyAction="http://tempuri.org/IService1/GetSistemaResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetSistemaAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSistemaByEmpresa", ReplyAction="http://tempuri.org/IService1/GetSistemaByEmpresaResponse")]
        AppControlCMMI.ControWS.ListItem[] GetSistemaByEmpresa(int idEmpresa, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSistemaByEmpresa", ReplyAction="http://tempuri.org/IService1/GetSistemaByEmpresaResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetSistemaByEmpresaAsync(int idEmpresa, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLiderKrio", ReplyAction="http://tempuri.org/IService1/GetLiderKrioResponse")]
        AppControlCMMI.ControWS.ListItem[] GetLiderKrio(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLiderKrio", ReplyAction="http://tempuri.org/IService1/GetLiderKrioResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetLiderKrioAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPMOKrio", ReplyAction="http://tempuri.org/IService1/GetPMOKrioResponse")]
        AppControlCMMI.ControWS.ListItem[] GetPMOKrio(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPMOKrio", ReplyAction="http://tempuri.org/IService1/GetPMOKrioResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetPMOKrioAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEnlace", ReplyAction="http://tempuri.org/IService1/GetEnlaceResponse")]
        AppControlCMMI.ControWS.ListItem[] GetEnlace(int idEmpresa, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEnlace", ReplyAction="http://tempuri.org/IService1/GetEnlaceResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetEnlaceAsync(int idEmpresa, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDesarrolladorKrio", ReplyAction="http://tempuri.org/IService1/GetDesarrolladorKrioResponse")]
        AppControlCMMI.ControWS.ListItem[] GetDesarrolladorKrio(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDesarrolladorKrio", ReplyAction="http://tempuri.org/IService1/GetDesarrolladorKrioResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetDesarrolladorKrioAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPPQAKrio", ReplyAction="http://tempuri.org/IService1/GetPPQAKrioResponse")]
        AppControlCMMI.ControWS.ListItem[] GetPPQAKrio(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPPQAKrio", ReplyAction="http://tempuri.org/IService1/GetPPQAKrioResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetPPQAKrioAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdminConfKrio", ReplyAction="http://tempuri.org/IService1/GetAdminConfKrioResponse")]
        AppControlCMMI.ControWS.ListItem[] GetAdminConfKrio(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdminConfKrio", ReplyAction="http://tempuri.org/IService1/GetAdminConfKrioResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetAdminConfKrioAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsuariosPuesto", ReplyAction="http://tempuri.org/IService1/GetAllUsuariosPuestoResponse")]
        AppControlCMMI.ControWS.ListItem[] GetAllUsuariosPuesto(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsuariosPuesto", ReplyAction="http://tempuri.org/IService1/GetAllUsuariosPuestoResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetAllUsuariosPuestoAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsuariosAnexos", ReplyAction="http://tempuri.org/IService1/GetAllUsuariosAnexosResponse")]
        AppControlCMMI.ControWS.ListItem[] GetAllUsuariosAnexos(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsuariosAnexos", ReplyAction="http://tempuri.org/IService1/GetAllUsuariosAnexosResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetAllUsuariosAnexosAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reporte", ReplyAction="http://tempuri.org/IService1/ReporteResponse")]
        AppControlCMMI.ControWS.DataRepTicket[] Reporte(string Nombre, string Ticket, int Sistema, int idEmpleado, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reporte", ReplyAction="http://tempuri.org/IService1/ReporteResponse")]
        System.Threading.Tasks.Task<AppControlCMMI.ControWS.DataRepTicket[]> ReporteAsync(string Nombre, string Ticket, int Sistema, int idEmpleado, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarDireccionSNV", ReplyAction="http://tempuri.org/IService1/AgregarDireccionSNVResponse")]
        void AgregarDireccionSNV(int idTicket, int idUsuario, int idSVN, string Ruta, string URL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarDireccionSNV", ReplyAction="http://tempuri.org/IService1/AgregarDireccionSNVResponse")]
        System.Threading.Tasks.Task AgregarDireccionSNVAsync(int idTicket, int idUsuario, int idSVN, string Ruta, string URL);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregaTicket", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AgregaTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AppControlCMMI.ControWS.Ticket _Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string key;
        
        public AgregaTicketRequest() {
        }
        
        public AgregaTicketRequest(AppControlCMMI.ControWS.Ticket _Ticket, string Mensaje, string key) {
            this._Ticket = _Ticket;
            this.Mensaje = Mensaje;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregaTicketResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AgregaTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AppControlCMMI.ControWS.Ticket AgregaTicketResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Mensaje;
        
        public AgregaTicketResponse() {
        }
        
        public AgregaTicketResponse(AppControlCMMI.ControWS.Ticket AgregaTicketResult, string Mensaje) {
            this.AgregaTicketResult = AgregaTicketResult;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AppControlCMMI.ControWS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AppControlCMMI.ControWS.IService1>, AppControlCMMI.ControWS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppControlCMMI.ControWS.UsuarioSVN ObtenerUsuarioSVN(int idUsuario, string key) {
            return base.Channel.ObtenerUsuarioSVN(idUsuario, key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.UsuarioSVN> ObtenerUsuarioSVNAsync(int idUsuario, string key) {
            return base.Channel.ObtenerUsuarioSVNAsync(idUsuario, key);
        }
        
        public bool AgregarUsuarioSVN(AppControlCMMI.ControWS.UsuarioSVN uSVN, string key) {
            return base.Channel.AgregarUsuarioSVN(uSVN, key);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarUsuarioSVNAsync(AppControlCMMI.ControWS.UsuarioSVN uSVN, string key) {
            return base.Channel.AgregarUsuarioSVNAsync(uSVN, key);
        }
        
        public AppControlCMMI.ControWS.UsuarioFirmado Acceso(AppControlCMMI.ControWS.Usuario user, string key) {
            return base.Channel.Acceso(user, key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.UsuarioFirmado> AccesoAsync(AppControlCMMI.ControWS.Usuario user, string key) {
            return base.Channel.AccesoAsync(user, key);
        }
        
        public AppControlCMMI.ControWS.Menu[] Menu(int idPerfil, string key) {
            return base.Channel.Menu(idPerfil, key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.Menu[]> MenuAsync(int idPerfil, string key) {
            return base.Channel.MenuAsync(idPerfil, key);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppControlCMMI.ControWS.AgregaTicketResponse AppControlCMMI.ControWS.IService1.AgregaTicket(AppControlCMMI.ControWS.AgregaTicketRequest request) {
            return base.Channel.AgregaTicket(request);
        }
        
        public AppControlCMMI.ControWS.Ticket AgregaTicket(AppControlCMMI.ControWS.Ticket _Ticket, ref string Mensaje, string key) {
            AppControlCMMI.ControWS.AgregaTicketRequest inValue = new AppControlCMMI.ControWS.AgregaTicketRequest();
            inValue._Ticket = _Ticket;
            inValue.Mensaje = Mensaje;
            inValue.key = key;
            AppControlCMMI.ControWS.AgregaTicketResponse retVal = ((AppControlCMMI.ControWS.IService1)(this)).AgregaTicket(inValue);
            Mensaje = retVal.Mensaje;
            return retVal.AgregaTicketResult;
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.AgregaTicketResponse> AgregaTicketAsync(AppControlCMMI.ControWS.AgregaTicketRequest request) {
            return base.Channel.AgregaTicketAsync(request);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetEmpresa(string key) {
            return base.Channel.GetEmpresa(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetEmpresaAsync(string key) {
            return base.Channel.GetEmpresaAsync(key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetTipo(string key) {
            return base.Channel.GetTipo(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetTipoAsync(string key) {
            return base.Channel.GetTipoAsync(key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetSistema(string key) {
            return base.Channel.GetSistema(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetSistemaAsync(string key) {
            return base.Channel.GetSistemaAsync(key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetSistemaByEmpresa(int idEmpresa, string key) {
            return base.Channel.GetSistemaByEmpresa(idEmpresa, key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetSistemaByEmpresaAsync(int idEmpresa, string key) {
            return base.Channel.GetSistemaByEmpresaAsync(idEmpresa, key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetLiderKrio(string key) {
            return base.Channel.GetLiderKrio(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetLiderKrioAsync(string key) {
            return base.Channel.GetLiderKrioAsync(key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetPMOKrio(string key) {
            return base.Channel.GetPMOKrio(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetPMOKrioAsync(string key) {
            return base.Channel.GetPMOKrioAsync(key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetEnlace(int idEmpresa, string key) {
            return base.Channel.GetEnlace(idEmpresa, key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetEnlaceAsync(int idEmpresa, string key) {
            return base.Channel.GetEnlaceAsync(idEmpresa, key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetDesarrolladorKrio(string key) {
            return base.Channel.GetDesarrolladorKrio(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetDesarrolladorKrioAsync(string key) {
            return base.Channel.GetDesarrolladorKrioAsync(key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetPPQAKrio(string key) {
            return base.Channel.GetPPQAKrio(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetPPQAKrioAsync(string key) {
            return base.Channel.GetPPQAKrioAsync(key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetAdminConfKrio(string key) {
            return base.Channel.GetAdminConfKrio(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetAdminConfKrioAsync(string key) {
            return base.Channel.GetAdminConfKrioAsync(key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetAllUsuariosPuesto(string key) {
            return base.Channel.GetAllUsuariosPuesto(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetAllUsuariosPuestoAsync(string key) {
            return base.Channel.GetAllUsuariosPuestoAsync(key);
        }
        
        public AppControlCMMI.ControWS.ListItem[] GetAllUsuariosAnexos(string key) {
            return base.Channel.GetAllUsuariosAnexos(key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.ListItem[]> GetAllUsuariosAnexosAsync(string key) {
            return base.Channel.GetAllUsuariosAnexosAsync(key);
        }
        
        public AppControlCMMI.ControWS.DataRepTicket[] Reporte(string Nombre, string Ticket, int Sistema, int idEmpleado, string key) {
            return base.Channel.Reporte(Nombre, Ticket, Sistema, idEmpleado, key);
        }
        
        public System.Threading.Tasks.Task<AppControlCMMI.ControWS.DataRepTicket[]> ReporteAsync(string Nombre, string Ticket, int Sistema, int idEmpleado, string key) {
            return base.Channel.ReporteAsync(Nombre, Ticket, Sistema, idEmpleado, key);
        }
        
        public void AgregarDireccionSNV(int idTicket, int idUsuario, int idSVN, string Ruta, string URL) {
            base.Channel.AgregarDireccionSNV(idTicket, idUsuario, idSVN, Ruta, URL);
        }
        
        public System.Threading.Tasks.Task AgregarDireccionSNVAsync(int idTicket, int idUsuario, int idSVN, string Ruta, string URL) {
            return base.Channel.AgregarDireccionSNVAsync(idTicket, idUsuario, idSVN, Ruta, URL);
        }
    }
}
